package com.virnanda.candiindonesia;

import java.util.ArrayList;

public class DataCandi {
    private static final String[] urutanCandi = {
            "Candi Singosari",
            "Candi Gambar Wetan",
            "Candi Penataran",
            "Candi Borobudur",
            "Candi Prambanan",
            "Candi Dieng",
            "Candi Badut",
            "Candi Lumbung",
            "Candi Gedong Songo",
            "Candi Simping",
            "Candi Jawi",
            "Candi Mendut",
            "Candi Sojiwan",
            "Candi Jabung",
            "Candi Cangkuang",
            "Candi Bajang Ratu",
            "Candi Belahan",
            "Candi Gunung Gangsir",
            "Candi Goa Gajah",
            "Candi Pari",
            "Candi Surawana",
            "Candi Plaosan",
            "Candi Sukuh",
            "Candi Selogriyo",
            "Candi Tebing Gunung Kawi",
            "Candi Asu Sengi",
            "Candi Ratu Boko",
            "Candi Banyunibo",
            "Candi Ngetos",
            "Candi Wringin Branjang",
            "Candi Kidal",
            "Candi Wringin Lawang",
            "Candi Tegowangi",
            "Candi Morangan",
            "Candi Bubrah",
            "Candi Sewu",
            "Candi Ngawen"
    };

    private static String detailCandi[] = {
            "Jl. Kertanegara No.148, Kec. Singosari, Kabupaten Malang, Jawa Timur (65153).\n\nCandi singosari ini terletak di Desa Candi Renggo, Kecamatan Singosari, Kabupaten Malang dengan jarak kurang lebih sekitar 9 km dari kota Malang ke arah Surabaya. Nama lain candi ini adalah Candi Cungkup atau Candi Menara, nama yang menunjukkan bahwa Candi Singasari merupakan candi tertinggi yang ada di sekitarnya. Akan tetapi di sekitar Kecamatan Singasari hanya Candi Singari lah yang masih tersisa dan yang lein telah lenyap.\n\nPara ahli purbakala memperkirakan bahwa Candi Singasari dibangun pada 1300 M, sebagai penghormatan kepada Raja Kertanegara. Terdapat dua candi yang digunakan untuk penghormatan yaitu Candi Jawi dan Candi Singasari.Candi Singasari merupakan candi beraliran syiwa. Hal ini terlihat pada beberapa arca Syiwa yang ada di halaman candi.",
            "Dsn. Sumberasri, Kec. Nglegok, Kab. Blitar, Jawa Timur (66181).\n\nCandi Gambar Wetan terletak lereng Gunung Kelud tepatnya di Perkebunan Gambar, Desa Sumberasri, Kecamatan Nglegok, Kabupaten Blitar, Jawa Timur. Candi Gambar Wetan dalam keadaan tidak utuh. Yang tersisa hanyalah batur candi dengan relief yang masih tersisa. Bagian lain dari komponen areal ini adalah dwarapala yang berjumlah dua buah yang menjaga tangga masuk menuju candi.\n\nCandi Gambar Wetan terletak di puncak bukit dengan dwarapala yang menjaga pada tangganya. Candi ini diperkirakan berasal dari masa Kerajaan Majapahit. Candi Gambar Wetan dipercaya merupakan tempat peristirahatan Hayam Wuruk dan raja Majapahit lain dalam perjalanannya menuju Gunung Kelud ataupun Candi Penataran.\n\nKetika ditemukan pertama kali oleh petugas perkebunan, cangkul petugas perkebunan mengenai sisi candi dan ditemukan arca. Selanjutnya dilakukan penggalian pada tahun 1992. Kata petugas, di candi ini pernah ditemukan relief Werkudara di Dam Sangiran. Namun sebelum candi ini diresmikan oleh pemerintah, banyak terjadi penjarahan oleh warga yang mengambil relief dari Candi Gambar Wetan. Pada zaman penjajahan Belanda, relief candi banyak diambil guna dijadikan pajangan di rumah Direksi Kebesaran. Namun kini patung relief telah diambil alih pemerintah serta diamankan ke museum dan dimasukkan ke Trowulan.",
            "Desa. Penataran, Kec. Nglegok, Kab. Blitar, Jawa Timur (66181).\n\nCandi Penataran merupakan salah satu candi di Blitar dengan corak relief, arca dan struktur bergaya Hindu. Candi Penataran berlokasi di Desa Penataran, Kecamatan Nglegok, Kota Blitar, Provinsi Jawa Timur. Bukti bahwa candi ini bercorak Hindu adalah adanya pahatan Kala (raksasa menyeringai), Patung Dwarapala (Raksasa penjaga pintu gerbang), arca Ganesha (perlambang dewa ilmu pengetahuan dalam mitologi Hindu), dan relief Ramayana. Selain bernama Candi Penataran atau Panataran, beberapa ahli menganggap bahwa candi ini bernama Candi Palah.\n\nCandi Penataran dibangun pada tahun 1194 yang tergambar pada Prasasti Palah yang ada di area Candi Penataran yang menyebutkan bahwa candi ini mulai dibangun pada pemerintahan raja Syrenggra Kerajaan Kediri dan selesai pada masa pemerintahan Majapahit. Dengan begitu dapat dikatakan bahwa kerajaan ini dibangun pada tiga masa yaitu masa Kerajaan Kediri, masa Kerajaan Singosari, dan masa Kerajaan Majapahit. Candi ini memiliki peran penting dalam ketiga kerajaan tersebut yaitu sebagai tempat pengangkatan raja serta sebagai tempat diadakannya upacara pemujaan bagi Sang Pencipta.",
            "Jl. Badrawati, Kw. Candi Borobudur, Borobudur, Kec. Borobudur, Kab. Magelang, Jawa Tengah.\n\nCandi Borobudur terletak di Kabupaten Magelang, berjarak 15 km dari Yogyakarta. Borobudur terletak di bukit Menoreh serta dikelilingi oleh gunung – gunung besar seperti Merbabu, Merapi, Sindoro dan Sumbing. Candi ini pun dekat dengan Candi Mendut yaitu berjarak 3 km. Borobudur merupakan peninggalan Dinasti Syailendra dari abad ke – 9 M. Selain nama Borobudur juga disebut Barabudhur dalam sejarahnya.\n\nBerdasarkan perbandingan analisa antara aksara yang ada di Karmawibhangga dan jenis aksara yang lazim digunakan pada abad ke 8 hingga ke 9 Masehi, diperkirakan candi ini dibangun pada sekitar tahun 800 masehi. Hal ini termasuk dalam kurun waktu kejayaan pemerintahan wangsa Syailendra yaitu pada 760 M hingga 830 Masehi. Pembangunan Candi Borobudur baru terselesaikan pada masa pemerintahan Raja Samaratungga yaitu sekitar tahun 825 Masehi. Belum terlalu jelas mengenai bukti peninggalan sejarah dari Borobudur dan hanya beberapa prasasti saja yang menyinggung mengenai keberadaan Candi Borobudur. Borobudur diduga dirancang oleh seorang arsitek terkenal pada masa lalu yaitu yang bernama Gunadharma. Dan diperkirakan pembangunan Candi Borobudur selesai saat Dinasti Syailendra dengan raja pada masa pemerintahan Raja Samaratungga.",
            "Jl. Raya Solo - Yogyakarta No.16, Kranggan, Bokoharjo, Kec. Prambanan, Kab. Sleman, Daerah Istimewa Yogyakarta (55571).\n\nCandi Prambanan merupakan candi Hindu terbesar di Indonesia yang terletak di Desa Bokoharjo, Kecamatan Prambanan, Kabupaten Sleman, Yogyakarta. Uniknya, pintu gerbang dari candi ini terletak di provinsi yang berbeda yakni Desa Tlogo, Kecamatan Prambanan, Klaten, Jawa Tengah. Lokasi dari candi ini tak jauh dari jalan raya, hanya sekitar 100 meter dari jalan raya Solo – Yogya. Candi Prambanan belum diketahui secara pasti kapan dibangunnya, sebagian ahli menduga bahwa Candi Prambanan dibangun pada pertengahan abad ke – 9 oleh Wangsa Sanjaya tepatnya pada pemerintahan Raja Bitung Maha Sambu. Hal ini diceritakan oleh Prasasti Syiwargha yang ditemukan di sekitar Candi Prambanan yang sekarang tersimpan di Taman Nasional di Jakarta. Prasasti ini menerangkan pembangunan Candi Prambanan adalah tahun 788 Saka atau 856 Masehi dan ditulis pada masa pemerintahan Rakai Pikatan.\n\nProses pemugaran candi memakan waktu yang panjang seiring waktu ditemukan candi – candi di sekitar bangunan utama Candi Prambanan. Bangunan terbesar yaitu Candi Syiwa dilaporkan oleh C.A. Lons pada tahun 1733 dan kemudian dilakukan penggalian dan pencatatatan oleh Groneman dan selanjutnya diselesaikan pada tahun 1885. Upaya tersebut meliputi pembersihan semak belukar dan mengelompokkan batu – batu reruntuhan candi. Pada tahun 1902 van Erp melanjutkan upaya pengelompokan batu – batu Candi Prambanan lebih rinci. Pada tahun 1918 dilakukan kembali pemugaran oleh Dinas Purbakala Belanda (Oudheikundige Dienst) dengan merekonstruksi bangunan Candi Syiwa dibawah pimpinan P.J. Perquin.",
            "Jl. Dieng No.km 19, Sidorejo, Tieng, Kec. Kejajar, Kab. Wonosobo, Jawa Tengah (56325).\n\nCandi Dieng merupakan sebuah kompleks Candi yang berada di dataran tinggi dieng yang berada pada ketinggian 2000 meter diatas permukaan laut. Kompleks Candi ini juga merupakan salah satu candi tertua di Jawa yang dibangun sekitar abad ke 7 hingga abad ke-9 Masehi. Area kompleks candi ini juga memiliki wilayah yang cukup luas, memiliki panjang hampir 1900 meter dan lebar sekitar 800 meter. Candi Dieng merupakan candi peninggalan agama hindu yang beraliran syiwa, diperkirakan dibangun pada masa pemerintahan kerajaan Kalingga pada masa dinasti Wangsa Sanjaya.\nCandi dieng terdiri dari delapan candi yang berukuran kecil. Hingga saat ini, nama candi dan sejarah berdirinya candi-candi di Dieng masih menjadi misteri, karena minimnya sumber dan masih sedikitnya penemuan prasasti-prasasti yang mengungkap sejarah di balik berdirinya candi tersebut. Namun, masyarakat lokal menamainya dengan tokoh-tokoh pewayangan yang terkenal, seperti Arjuna, Gatutkaca, Dwarawati, dan Bima. Sejarah Candi Dieng diawali dengan penemuan sebuah prasasti yang berangka tahun 808. Prasasti tersebut merupakan prasasti tertua dengan tulisan Jawa Kuno. Jadi para ilmuwan menyimpulkan Candi Dieng dibangun pada pemerintahan raja-raja Wangsa Sanjaya. Di kawasan candi dieng juga ditemukan arca dewa Syiwa yang saat ini di simpan di Museum Nasional Jakarta.",
            "Jl. Candi V No.5D, Doro, Karangwidoro, Kec. Dau, Kota Malang, Jawa Timur (65146).\n\nCandi Badhut terletak di Desa Karangbesuki, Kecamatan Dau, Kabupaten Malang, Jawa Timur. Candi ini ditemukan pada tahun 1923 oleh pakar arkeologi. Diperkirakan candi ini dibangun jauh sebelum pemerintahan Airlangga, yaitu masa awal pembangunan candi – candi yang ada di Jawa Timur serta diduga merupakan candi tertua di Jawa Timur. \n\nSebagian ahli purbakala mengatakan bahwa candi ini dibangun atas perintah dari Raja Kanjuruhan bernama Raja Gajayana. Pada Prasasti Dinoyo yang berangka tahun 682 saka atau 760 masehi yang ditemukan di Desa Merjosari, Malang menyebutkan bahwa pusat dari Kerajaan Kanjuruhan adalah daerah Dinoyo.\n\nPrasasti Dinoyo kini tersimpan di Museum Nasional Jakarta. Tulisan dalam prasasti ini menyebutkan bahwa masa keemasan Kerajaan Kanjuruhan adalah pada masa pemerintahan Raja Dewasimba dan putranya yang bernama Sang Liswa. Keduanya dalam memimpin kerajaan sangat adil dan bijaksana. Konon Raja Sang Liswa merupakan raja yang senang melucu atau dalam bahasa Jawa disebut mbadut, sehingga candi yang Sang Liswa bangun dinamakan Candi Badhut. Walaupun demikian hingga saat ini belum ditemukan bukti adanya hubungan dengan Raja Gajayana.",
            "Nngangrukbaru, Tlogo, Kec. Prambanan, Kab. Sleman, Daerah Istimewa Yogyakarta (57454).\n\nCandi Lumbung merupakan candi yang terletak di kawasan Prambanan, tepatnya di Dukuh Bener, Desa Bugisan, Kecamatan Prambanan, Kabupaten Klaten, Jawa Tengah. Candi ini merupakan salah satu candi yang masuk dalam Kawasan Warisan Dunia Prambanan. Candi Lumbung merupakan candi Buddha yang diperkirakan dibuat di sekitar abad ke-9 sampai abad ke-10, tepatnya pada saat masih dikuasai oleh kerajaan Mataram Kuno. Candi Lumbung adalah candi yang tak jauh berbeda ataupun berhubungan dengan Candi Sewu. Hal ini diketahui dari bentuk candi-candi perwaranya yang mirip dengan candi perwara di Sewu yaitu atapnya yang berbentuk stupa. Hal ini juga menunjukan bahwa Candi Lumbung berlatar belakang candi Buddha. Nama Lumbung sendiri masih belum jelas diketahui secara pasti. Nama tersebut merupakan sebutan masyarakat di sekitarnya karena bentuknya yang mirip lumbung (bangunan tempat penyimpanan padi). Di dekat Candi Lumbung pernah ditemukan prasasti yang dikenal dengan Prasasti Kelurak.\nMenurut Boechari, seorang ahli epigrafi, prasasti ini berhubungan dengan pendirian Candi Sewu, mengingat adanya pendirian kirtistambha untuk Dewa Manjusri yang merupakan Dewa utama di Candi Sewu. Candi Lumbung belum diketahui, apakah didirikan oleh Sri Maharaja Rakai Panangkaran seperti halnya Candi Sewu, belum dapat dijelaskan. Keadaan batu pada Prasasti Kelurak sudah sangat aus atau sudah sulit untuk dibaca, sehingga isi keseluruhannya kurang diketahui. Namun, secara garis besar prasasti Kelurak ini berisi tentang didirikannya sebuah bangunan suci untuk arca Manjusri atas perintah Raja Indra yang bergelar Sri Sanggramadhananjaya. Menurut para ahli, yang dimaksud dengan bangunan tersebut adalah Candi Sewu, yang terletak di Kompleks Percandian Prambanan. Nama raja Indra tersebut juga ditemukan pada Prasasti Ligor dan Prasasti Nalanda peninggalan kerajaan Sriwijaya. Prasasti ini kini disimpan dengan No. D.44 di Museum Nasional, Jakarta.",
            "Jln. Krajan, Banyukuning, Kec. Bandungan, Kab. Semarang, Jawa Tengah (50614).\n\nCandi Gedong Songo merupakan beberapa candi yang berkelompok hingga membentuk sebuah komplek percandian yang merupakan salah satu peninggalan agama Hindu. Lokasi candi ini di desa Candi, kecamatan Bandungan, Jawa Tengah. Secara geografis, letak candi ini berada di koordinat -7.210290, +110.342010, yang berada di ketinggian 1200 m di atas permukaan laut. Lokasi tepatnya di kaki Gunung Ungaran sehingga kesejukkan dapat dirasakan di area ini. Suhunya pun sekitar 19° – 27° Celcius. Letaknya 15 km dari kota Ambarawa dan 45 km dari kota Semarang. Candi Gedong Songo belum diketahui kapan dibangunnya candi ini hingga sekarang, bahkan para arkeolog pun belum bisa memecahkan problem ini. Sehingga candi ini sampai sekarang masih sering dijadikan sebagai bahan penelitian di bidang arkeologi. Namun, ada beberapa yang berpendapat bahwa candi ini dibangun di masa pemerintahan dinasti Sanjaya Hindu di Jawa yaitu sekitar abad ke-8. Hal ini pun ditinjau dari segi bangunannya dan coraknya.\nBentuk dan relief itu telah dijadikan bukti bahwa candi ini dibangun di masa pemerintahan dinasti Sanjaya. Hal inilah yang menguatkan mereka berpendapat bahwa candi ini di bangun pada abad ke-8. Namun, belum ada yang memastikan bahkan tahun pembangunan candi ini pun belum dikonvensionalkan oleh beberapa ahli.",
            "Jl. Candi Simping, Candi Simping, Sumberjati, Kec. Kademangan, Kab. Blitar, Jawa Timur (66161).\n\nCandi Simping atau masyarakat sekitar menyebutnya dengan nama Candi Sumberjati berlokasi di Dusun Krajan, Desa Sumberjati, Kecamatan Kademangan, Kabupaten Blitar. Berjarak sekitar tujuh kilomater dari Kota Blitar ke arah selatan. Berada dekat dengan pusat Kec. Kademangan, menjadikan candi ini memiki akses yang mudah serta fasilitas yang memadai untuk dikunjungi karena berada di tengah – tengah pemukiman warga. Berbeda dengan candi lain yang berdiri tegak dengan bagian bagian candinya, di Candi Simping ini hanya tersisa sebagian saja bahkan bisa dikatakan hampir rata dengan tanah. Namun, dari reruntuhan ini masih bisa dinikmati dan dipelajari sisa dari peradaban masa Kerajaan Majapahit.\n\nYang tersisa di candi ini hanya bagian batur atau dasar dari struktur candi yang masih terlihat utuh di tempatnya. Sedangkan bagian lain seperti bagian tubuh dan atap candi tercecer di sekitar candi. Candi ini menghadap ke barat yang ditandai dengan adanya undak atau tangga masuk menuju ruang utama pada candi. Ukuran dari bagian bawah candi atau dinamakan batur candi adalah panjang 7,5 meter, lebar 6 meter dan tinggi 0,75 meter dengan hiasan relief di sisi – sisinya berupa binatang binatang seperti singa, angsa, merak, burung garuda, babi hutan dan kera. Di tengah bangunan candi terdapat sebuah batu tempat abu jenazah Raden Wijaya disemayamkan berbentuk kubus yang memiliki panjang, lebar dan tinggi 75 cm. Pada bagian atas batu kubus tersebut ada relief bulus dan naga yang saling mengaitkan seolah mengitari batu ini.",
            "Jl. Candiwates, Jawi, Candi Wates, Kec. Prigen, Kab. Pasuruan, Jawa Timur (67157).\n\nCandi Jawi terletak di Desa Candi Wates, Kecamatan Prigen, Kabupaten Pasuruan, atau di kaki Gunung Welirang yang berjarak 31 km dari Kabupaten Pasuruan. Candi Jawi telah mengalami berkali – kali pemugaran, diantaranya pada tahun 1938 – 1941 ketika kondisinya runtuh. Namun pada pemugaran tersebut tidak dapat diselesaikan karena banyaknya bagian yang hilang dan baru disempurnakan pada pemugaran tahun 1975- 1980.\n\nKitab Negarakertagama pupuh 56 menyebutkan bahwa Candi Jawi didirikan atas perintah dari raja Kertanegara untuk tempat beribadah umat Syiwa Buddha. Raja Kertanegara merupakan penganut dari Syiwa Buddha dari Kerajaan Singasari. Selain sebagai tempat beribadah, Candi Jawi juga merupakan tempat perabuan jenazah Kertanegara. Hal terebut memang agak mengherankan mengingat letak Candi Jawi yang berjarak cukup jauh dengan pusat Kerajaan Singasari.\n\nHal tersebut diduga dengan alasan bahwa desa tersebut sangat patuh dengan Kertanegara serta memiliki penganut Syiwa Buddha yang sangat banyak. Dugaan tersebut juga didasari atas kejadian ketika Raden Wijaya, menantu Kertanegara yang dikejar oleh Jayakatwang, Raden Wijaya sempat bersembunyi di tempat ini sebelum akhirnya mengungsi ke Madura.",
            "Jl. Mayor Kusen, Sumberrejo, Mendut, Kec. Mungkid, Kab. Magelang, Jawa Tengah (56501).\n\nBelum bisa dipastikan kapan candi Mendut dibangun karena memang sumbernya belum akurat. Namun ada rujukan dari beberapa peneliti mengenai pembangunan candi mendut yaitu pada 824 M. Angka 824 M ini didapat oleh J.G. De Casparis atas dasar penemuan prasasti yang ditemukan di Karang Tengah yang menyebutkan bahwa raja Indra telah membangun bangunan suci bernama Venuwana.\n\nCasparis menyebutkan bahwa Venuwana berarti hutan bambu sedangkan daerah Candi Mendut sendiri dahulu adalah hutan bambu maka dapat disimpulkan bangunan suci tersebut adalah Candi Mendut. Diperkirakan candi mendut berusia lebih tua dari pada Candi Borobudur.",
            "Jl. Banjarsari No.12 RT. 03, RW.03, Kwaron, Kb. Dalem Kidul, Kec. Prambanan, Kab. Klaten, Jawa Tengah )57454).\n\nCandi Sojiwan atau Candi Sajiwan adalah salah satu dari banyaknya candi di Klaten. Candi ini terletak di Dukuh Kalongan, Desa Kebon Dalem Kidul, Kecamatan Prambanan, Kabupaten Klaten yang berada pada ketinggian 146 – 150 mdpl. Candi ini dianggap sebagai candi sebaran dari Candi Prambanan karena letaknya yang tak jauh dari Candi Prambanan yaitu sekitar dua kilometer ke arah tenggara.\n\nCandi Sojiwan memiliki luas yaitu 8.140 m persegi, luas bangunan utama candi memiliki luas 401,3 m persegi dan tinggi candi kurang lebih 27 m. Candi Sojiwan menghadap kearah barat. Terdapat dwarapala yang sudah rusak dan kini ditempatkan di pos penjagaan di komplek Candi Sojiwan. Pada bagian bawah candi terdapat ukiran relief kisah satwa Jataka sekitar 12 adegan mengelilingi dinding bawah candi. Cara membaca relief tersebut dengan membaca ke arah selatan (mapradaksina).",
            "Dsn. Candi, Jabung Candi, Kec. Paiton, Kab. Probolinggo, Jawa Timur (67291).\n\nCandi Jabung terletak di Desa Jabung, Kecamatan Paiton, Kabupaten Probolinggo, Jawa Timur. Candi Jabung merupakan peninggalan Kerajaan Majapahit yang dibangun pada tahun 1354 M. Pada kitab Negarakertagama dikatakan bahwa Raden Hayam Wuruk pernah mengunjungi Candi Jabung pada tahun 1359 M. Pada kitab Pararaton mengatakan bahwa diperkirakan candi ini dibangun untuk pemakaman Bhra Gundul salah seroang keluarga raja.\n\nCandi Jabung terdiri dari dua bangunan yaitu candi utama dan satu bangunan yang lebih kecil. Yang menarik dari candi ini adalah bahan dasarnya yang terbuat dari batu bata merah berkualitas tinggi yang diukir dalam bentuk relief. Struktur bangunan yang terbuat dari candi ini mampu bertahan hingga ratusan tahun.\n\nCandi utama terbuat dari batu bata merah dengan ukuran panjang 13,11 meter, lebar 9,58 meter dan tinggi 15,58 meter. Jika dilihat dari segi arsitekturnya, Candi Jabung memiliki keunikan yaitu bentuk tubuhnya yang berbentuk bulat (silinder) yang terdiri dari bagian kaki candi bertingkat tiga berbentuk persegi. Sedangkan pada bagian atap berbentuk stupa. Letak pintu bilik candi berada pada sisi sebelah barat, maka Candi Jabung menghadap arah barat.",
            "Desa. Leuwigoong Karanganyar, Cangkuang, Kec. Leles, Kab. Garut, Jawa Barat, (44119).\n\nCandi Cangkuang terletak di Kampung Pulo, Desa Cangkuang, Kecamatan Leles, Kabupaten Garut. Desa Cangkuang dikelilingi oleh empat gunung diantaranya Gunung Keledong, Gunung Mandalawangi, Gunung Haruman, dan Gunung Guntur. Nama “Cangkuang” pada Candi Cangkuang diambil dari nama tanaman sejenis pandan (pandanus furcatus) yang banyak ditemukan di sekitar makam Embah Dalem Arief Muhammad, seorang leluhur dari Kampung Pulo.\n\nPemugaran Candi Cangkuang dilakukan pada tahun 1974-1975 sedangkan rekonstruksi dilakukan pada tahun 1976 yang meliputi kerangka badan, atap dan arca Syiwa serta dibuatkan joglo yang berfungsi menyimpan benda – benda temuan bersejarah di  seluruh Kabupaten Garut. Kegiatan pemugaran pada tahun 1974 telah menemukan bagian kaki candi. Kendala dalam rekonstruksi candi adalah hanya ditemukan 40% bagian candi aslinya, sehingga dibutuhkan batuan pengganti untuk merekonstruksi candi.\n\nDiduga Candi Cangkuang dibangun pada abad ke – 8 yang didasarkan pada tingkat kelapukan batuan dan kesederhanaan bentuk (tidak adanya relief). Setelah dipugar, Candi Cangkuang memiliki tinggi 8,5 meter dengan kaki candi berukuran 4,5 x 4,5 meter. Atap candi berbentuk piramid. Sepanjang tepian atap candi terdapat semacam mahkota kecil yang memiliki kemiripan dengan atap candi yang ada di Candi Gedong Songo.",
            "Jl. Candi Tikus No.9, Pelem, Temon, Kec. Trowulan, Kab. Mojokerto, Jawa Timur (61362).\n\nCandi Bajangratu terletak di Dukuh Kraton, Desa Temon, Kecamatan Trowulan, Kabupaten Mojokerto. Penamaan Bajangratu pertamakali disebutkan oleh Oudheidkunding Verslag (OV)  pada tahun 1915. Menurut arkeolog Sri Soeyatmi Satari nama Bajangratu memiliki hubungan dengan Raja Jayanegara, sebeb nama Bajangratu pada kata “bajang” memiliki arti kerdil. Pada kitab Pararaton menyebutkan bahwa Jayanegara dinobatkan menjadi raja Kerajaan Majapahit ketika masih kecil (bajang), dan dari sinilah gelar Ratu Bajang atau Bajangratu melekat pada nama Jayanegara.\n\nCandi Bajangratu diperkirakan memiliki fungsi sebagai penghormatan kepada Jayanegara. Hal ini didasarkan pada relief Sri Tanjung yang berada di bagian kaki gapura yang menceritakan tentang cerita peruwatan. Kitab Pararaton menyebutkan bahwa Raja Jayanegara meninggal pada tahun 1328. Di kitab Pararaton juga disebutkan bahwa Jayanegara yang wafat pada tahun 1328 itu, dibuatkan sebuah tempat suci di dalam kedaton, dibuatkan arca dalam bentuk Wisnu di Shila Petak dan Bubat, serta dibuatkan arcanya dalam bentuk Amoghasidhi di Sukalila. Krom berpendapat bahwa Csrenggapura di kitab Pararaton sama dengan Antarasasi (Antarawulan) dalam kitab Negarakertagama, sehingga dari pernyataan tersebut dapat disimpulkan bahwa ‘dharma’ (tempat suci) Jayanegara terdapat di Csrenggapura atau Crirangga Pura atau Antarawulan, dengan nama sekarang yaitu Trowulan. Arca perwujudan Wisnu juga terdapat di Bubat (Trowulan).\n\nCandi Bajangratu memiliki konstruksi yang berasal dari bahan batu bata merah, kecuali bagian atap dan anak tangga. Candi ini menghadap ke dua arah yaitu barat dan timur dengan tinggi 16,1 M dan dengan panjang 6,74 m. Terdapat sayap di sebelah kanan dan kiri candi. Seperti candi pada umumnya, di bagian pintu terdapat kalamakara yang berada tepat diatas ambang pintu. Pada bagian kaki ambang pintu terdapat bekas lubang untuk kusen. Kemungkinan pintu candi ini dilengkapi dengan daun pintu.",
            "Desa. Belahan Jowo, Wonosunyo, Kec. Gempol, Kab. Pasuruan, Jawa Timur (67155).\n\nCandi Belahan terletak di Dusun Belahan, Desa Wonosonyo, Kecamatan Gempol, Pasuruan, Jawa Timur. Candi ini merupakan sebuah petirtaan yang memiliki keunikan yaitu adanya dua patung wanita Dewi Sri dan Dewi Laksmi. Patung Dewi Laksmi mengeluarkan air dari tetek (payudaranya) yang kemudian ditampung pada kolam berukuran 6 x 4 meter yang berada di bawah patung tersebut. Dari sinilah kemudian masyarakat selain menyebut Candi Belahan juga menyebutnya dengan Candi Sumber Tetek.\n\nKedua patung di Candi Belahan ini melambangkan kesuburan serta kemakmuran, kedua patung ini berdiri dan membelakangi dinding yang terbuat dari batu bata yang dihiasi relief yang menggambarkan sosok Dewa Wisnu yang menunggangi garuda setinggi sekitar tiga meter. Air yang keluar dari patung Dewi Laksmi mengalir sepanjang tahun, bahkan di musim kemarau sekalipun. Candi Belahan berada di ketinggian 700 mdpl dan merupakan candi yang belum pernah di pugar. Air yang bersumber dari tetek Dewi Laksmi sangat jernih dan hingga saat ini masih digunakan masyarakat sekitar untuk keperluan sehari – hari.\n\nMenurut warga sekitar, air dari patung Dewi Laksmi mempunyai khasiat seperti awet muda dan mampu menyembuhkan penyakit. Sosok penunggu kawasan Candi Belahan dipercaya menjaga situs pentirtaan Sumber Tetek ini. Konon, pada masa kolonialisme Belanda banyak patung di Candi Belahan yang diangkut Belanda dan dijadikan koleksi museum Belanda. Meskipun Candi Belahan belum mengalami pemugaran, Candi Belahan atau Petirtaan Sumber Tetek sangat layak dijadikan destinasi wisata. Adanya kedua patung tersebut menambah nilai artistik dan budaya di kawasan ini.",
            "Dsn. Kebon Candi, RT.02/RW.10, Gununggangsir, Gn. Gangsir, Kec. Beji, Kab. Pasuruan, Jawa Timur (67154).\n\nCandi Gunung Gangsir terletak di Desa Gunung Gangsir, Kecamatan  Beji, Pasuruan Jawa Timur atau terletak 18 km dari Kota Pasuruan. Candi ini sebenarnya bernama Candi Keboncandi, penamaan Gunung Gangsir karena keberadaannya yang terletak di Desa Gunung Gangsir. Candi ini diperkirakan dibangun pada abad ke 11 M pada masa pemerintahan Raja Airlangga. Candi Gunung Gangsir dibangun dari bahan dasar batu bata merah. Candi Gunung Gangsir tidak jelas mengenai fungsinya.\n\nMenurut masyarakat sekitar Candi Gunung Gangsir dibangun untuk penghormatan Nyi Sri Gati yang dijuluki Mbok Randa Derma (Janda Murah Hati), atas jasanya membangun masyarakat pertanian di daerah tersebut. Nyi Sri Gati merupakan tokoh dalam legenda setempat.",
            "Jln. Bedulu - Blahbatuh, Gianyar Regency, Bali, Jawa Barat.\n\nCandi Goa Gajah merupakan salah satu destinasi wisata sejarah yang terletak di Desa Bedulu, Kecamatan Blahbatu, Kabupaten Gianyar. Jarak dari Denpasar menuju Goa Gajah adalah 27 Km. Pengambilan kata Goa Gajah diambil dari kata Lwa Gajah yang berarti sungai gajah yang dapat diartikan bahwa tempat tersebut adalah tempat pertapaan yang berada di sungai. Nama Goa Gajah sendiri diambil dari kitab negarakertagama karangan Empu Prapanca pada tahun 1365 M. Goa Gajah dibangun sekitar abad ke 11 M ketika masa pemerintahan raja Sri Bedulu yang pada saat itu pula bersamaan dengan masa kejayaan Majapahit yang dipimpin oleh Hayam Wuruk.\n\nSecara keseluruhan struktur pura Goa Gajah berbeda dengan pura lainnya di Bali, yang pada umumnya terdiri atas Jaba atau halaman luar, Jaba Tengah atau halaman tengah dan Jeroan atau halaman belakang yang menjadi tempat paling suci dalam suatu pura. (Papan Informasi Goa Gajah).\n\ndapat diperkirakan bahwa Goa Gajah telah berdiri pada abad ke-11 Masehi, yaitu pada masa pemerintahan Anak Wungsu. Namun jika menilik pada peninggalan yang bersifat Buddhisme yang terdapat di Goa Gajah, yaitu Arca Dyani Buddha Amitaba yang menurut langgamnya banyak menunjukan persamaan dengan Arca Dyani Buddha pada candi Borobudur yaitu dari pertengahan abad ke-9 masehi, maka dapat disimpulkan bahwa kemungkinan Goa Gajah telah berdiri jauh sebelum masa pemerintahan Anak Wungsu dengan embrio awalnya sebagai tempat ibadah agama Buddha dan baru pada abad ke-11 Masehi agama Hindu turut membangun kompleks peribadatan di tempat ini.",
            "Jl. Purbakala, Porong, Kec. Porong, Kab. Sidoarjo, Jawa Timur (61274).\n\nCandi Pari terletak di Desa Candi Pari, Kecamatan Porong, Kabupaten Sidoarjo, Jawa Timur. Candi Pari merupakan candi berbahan batu bata yang berbentuk segi empat, menghadap ke barat dengan ambang serta tutup gerbang terbuat dari batu andesit. Dahulu diatas gerbang terdapat batu yang menunjukkan tahun pembuatan candi yaitu angka tahun 1293 Saka atau 1371 M. Tahun tersebut merupakan masa pemerintahan Hayam Wuruk di Kerajaan Majapahit.\n\nCandi Pari berbentuk tambun dan memiliki kemiripan dengan candi – candi di Jawa Tengah. Candi Pari memiliki tinggi 15,40 m, panjang 16 m, dan lebar 14,10 m. Candi ini bisa dikataka dalam keadaan utuh, kaki dan badan candi masih ada hanya atap candi yang sudah tidak ada. Candi Pari minim sekali akan hiasan atau relief. Hiasan yang ada hanya miniatur candi yang menjorok keluar dari badan candi. Diatas miniatur candi terdapat hiasan berupa teratai. Pada bagian kanan dan kiri miniatur candi terdapat lubang angin yang menembus ke dalam bilik candi. Pada atap candi sebenarnya terdapat hiasan binatang, namun kini dalam keadaan aus.\n\nCandi Pari memiliki keunikan selain bentuknya yang tambun, keunikan lainnya terletak pada tangga candi. Jika pada umumnya tangga candi langsung menuju ke biilk candi, maka hal tersebut tidak berlaku di Candi Pari. Untuk menuju bilik candi sebelumnya akan ada sebuah bidang persegi (batur) yang menjorok keluar dari bawah pintu candi (hal ini mirip dengan yang ada di Candi Ngetos dan Candi Bangkal). Pada bagian kanan dan kiri batur terdapat tangga dengan pipi tangga (tempat pegangan) dalam kondisi yang telah runtuh. Pada beberapa sudut halaman candi juga terdapat reruntuhan batu – bata yang diperkirakan merupakan pagar yang mengelilingi Candi Pari.",
            "Desa. Surowono, Canggu, Kec. Badas, Kab. Kediri, Jawa Timur (64217).\n\nCandi Surawana terletak di Desa Canggu, Kecamatan Pare, Kabupaten Kediri, atau berjarak 25 km ke arah laut dari Kota Kediri. Candi ini sesungguhnya adalah Wishnubhawanapura yang diperkirakan didirikan pada abad ke 14 untuk memuliakan Bhre Wengker, raja Kerajaan Wengker yang menjadi bagian dari Kerajaan Majapahit. Bhre Wengker ini kemudian meninggal pada tahun 1388 M. Kitab Negarakertagama menceritakan pada tahun 1361, Raja Majapahit Hayam Wuruk bahkan pernah menginap di Candi Suwana.\n\nCandi Surawana memiliki ukuran 8×8 m2. Candi Surawana menggunakan batu andesit dan merupakan candi beraliran Syiwa. Candi ini dalam keadaan hancur dan hanya tersisa kaki candi yang memiliki tinggi 3m yang masih berdiri. Untuk menaiki selasar terdapat tangga yang sempit dan terletak di sisi barat. Dari letak tersebut dapat di simpulkan bahwa Candi Suwana menghadap ke barat.\n\nPada bagian kaki candi bagian bawah mengisahkan tentang tantri, sedangkan bagian atas mengisahkan tentang Kisah Sri Tanjung, Arjunawiwaha, serta kisah Bubuksah dan Gagak Aking. Kisah – kisah seperti ini biasanya dibangun pada candi – candi dengan tujuan peruwatan, seperti yang ada di Candi Bajangratu serta Candi Tegawangi.",
            "Jl. Candi Plaosan, Plaosan Lor, Bugisan, Kec. Prambanan, Kab. Klaten, Jawa Tengah (57454).\n\nCandi Plaosan terletak di Desa Bugisan, Kecamatan Prambanan, Kabupaten Klaten. Candi Plaosan terbagi menjadi dua komplek yaitu Plaosan Lor (lor berarti utara) dan Plaosan Kidul (kidul berarti selatan). Relief  yang ada di Candi Plaosan sangat halus dan rinci layaknya relief yang ada di Candi Borobudur, Candi Sewu serta Candi Sari.\n\nCandi Plaosan yang beraliran Buddha ini menurut para ahli mulai dibangun pada masa Rakai Pikatan dari Kerajaan Mataram Hindu pada awal abad ke 9 Masehi. Hal ini di dukung oleh catatan De Casparis yang berpegang pada Prasasti Cri Kahulunan (842 M). Prasasti tersebut menceritakan bahwa Candi Plaosan Lor dibangun oleh Ratu Sri Kahulunan dengan suaminya. De Casparis berpendapat, Sri Kahulunan  merupakan gelar Pramordhawardani, putri dari Raja Samaratungga dari Wangsa Syailendra. Sang putri yang beragama Buddha menikahi Rakai Pikatan yang memeluk agama Hindu.\n\nPendapat lain mengenai pembangunan Candi Plaosan adalah pembangunan candi yang dimulai sebelum masa pemerintahan Rakai Pikatan. Anggraeini berpendapat, Sri Kahulunan merupakan ibu Rakai Garung yang memerintah Mataram sebelum Rakai Pikatan. Ia juga berpendapat bahwa pemerintahan Rakai Pikatan yang terlalu singkat tidak memungkinkan untuk membangun candi sebesar Candi Plaosan. Rakai Pikatan mendirikan candi perwara setelah masa pembangunan candi utamanya.",
            "Jl. Tambak, Berjo, Kec. Ngargoyoso, Kab. Karanganyar, Jawa Tengah (57793).\n\nCandi Sukuh terletak di lereng Gunung Lawu yaitu di Dusun Sukuh, Desa Berjo, Kecamatan Ngargoyoso, Kabupaten Karanganyar, Jawa Tengah. Candi Sukuh berada pada ketinggian 900 mdpl. Candi ini ditemukan oleh Johnson, seorang Residen Surakarta pada masa pemerintahan Raffles pada tahun 1815. Kemudian pada 1842 candi ini diteliti oleh Van der Vlis. Hasil dari penelitian Van der Vlis yang dimasukkan di dalam buku Van der Vlis yang berjudul Prove Eener Beschrijten op Soekoh en Tjeto. Penelitian tersebut kemudian dilanjutkan oleh Hoepermans pada 1864 sampai 1867 dan kemudian dibukukan dalam bukunya yang berjudul Hindoe Oudheiden van Java. Pada 1889, Verbeek melakukan inventarisasi Candi Sukuh, yang kemudian diteruskan dengan penelitian oleh Knebel dan WF.STutterheim pada 1910.\n\nCandi Sukuh bercorak Hindu dan diperkirakan didirikan pada akhir abad ke-15 M. Bentuk arsitektur Candi Sukuh sangat berbeda dengan candi – candi lain, candi ini dinilai menyimpang dari ketentuan pembangunan candi bangunan suci Hindu, Wastu Widya. Menurut aturan pembuatan candi, alas dari candi harus berdenah dasar bujur sangkar dengan tempat yang dianggap paling suci berada pada tengah ataupun tubuh candi. Perbedaan yang mencolok ini dikira pengaruh dari memudarnya pengaruh Hindu di Jawa. Memudarnya ajaran agama Hindu ini kemudian dikaitkan dengan berkembangnya kembali unsur budaya setempat yaitu Megalitikum. Unsur dari zaman Megalitikum sangat terlihat sekali di bangunan Candi Sukuh yaitu adanya punden berundak yang menjadi ciri khas bangunan masa pra-Hindu. Ciri lain dari bangunan pra-Hindu adalah pada sebuah bangunan area paling suci berada pada bagian tertinggi dan paling belakang.\n\nMenurut para ahli, keberadaan Candi Sukuh diperkirakan merupakan tempat pengruwatan yaitu melepaskan kekuatan buruk yng mempengaruhi kehidupn seseorang akibat dari ciri tertentu yang dimilikinya. Perkiraan tersebut didasarkan pada adanya relief yang menceritakan cerita pengruwatan seperti Sudamala dan Garudheya, serta adanya arca kura – kura dan garuda yang terdapat di Candi Sukuh.",
            "Dsn. Windusari, Kec. Windusari, Kab. Magelang, Jawa Tengah (56152).\n\nCandi Selogriyo diperkirakan dibangun pada abad 9 Masehi, namun baru ditemukan di tahun 1835 Masehi oleh Residen Magelang yang menjabat di masa penjajahan Belanda, yang bernama Hartmann. Perlu diketahui bahwa saking banyaknya penemuan candi di Indonesia di masa penjajahan Belanda, maka pada tahun 1913, pemerintah Belanda membuat sebuah institusi yang bernama Oudheidkundige Diensr, atau disebut juga sebagai lembaga kepurbakalaan. Lembaga tersebut salah-satunya bertujuan untuk melestarikan candi-candi yang ada, kemudian didaftarkan, dan menjadi situs, atau cagar budaya, termasuk di dalamnya Candi Selogriyo Magelang.\n\nCandi Selogriyo pertamakali dipugar pada tahun 1955 hingga tahun 1957. Namun, terjadi peristiwa yang memporakporandakan sebagian besar bangunan Candi Selogriyo. Kemudian dimulai pada tahun 2000 dilakukan pemasangan ulang terhadap kondisi Candi Selogriyo yang terdampak longsor tersebut secara bertahap.Dan penataan tersebut baru selesai pada tahun 2019, tepatnya pada tanggal 10 November 2019.",
            "Jl. Br penaka, Tampaksiring, Kec. Tampaksiring, Kab. Gianyar, Bali (80552).\n\nCandi Tebing Gunung Kawi terletak di Banjar Paneka, Desa Tampaksiring, Kecamatan Tampaksiring, Gianyar, Bali. Candi ini dibangun pada abad ke 11 Masehi pada masa pemerintahan dinasti Udayana (Warmadewa). Candi ini diperkirakan mulai dibangun pada masa kepemimpinan Raja Sri Haji Paduka Dharmawangsa  Marakata Pangkaja Stanattunggadewa (944 – 948 saka atau 1025 – 1049 M) dan berakhir pada kepemimpinan Raja Anak Wungsu (971 – 999 saka / 1049-1080 M).\n\nPrasasti Tengkulak yang menyebutkan angka 945 saka atau 1023 masehi menyebutkan bahwa di tepi Sungai Pakerisan terdapat tempat pertapaan atau kantyangan yang bernama Amarawati. Para ahli arkeolog meyakini bahwa Amarawati adalah sebutan untuk Candi Tebing Gunung Kawi. Sepuluh Candi Gunung Kawi terletak pada tiga titik yaitu lima candi berada di sisi timur Sungai Tukad Pakerisan, dan sisanya tersebar di dua titik di sebelah barat sungai. Lima candi yang berada pada sisi timur Sungai Tukad dianggap sebagai bagian utama dari Candi Tebing Gunung Kawi.\n\nada bagian utara dari sisi barat Sungai Tukad Pakerisan, ada emat candi yang berderet dari utara sampai ke selatan serta menghadap ke arah Sungai Tukad Pakerisan. Kemudian terdapat satu candi yang ada di sisi selatan, yang berjarak 200 meter dari candi sebelah utara. Menurut sejarah, Candi Tebing Gunung Kawi merupakan tempat pemujaan bagi Raja Udayana yang dibangun oleh anak keduanya Raja Marakarta. Anak pertamnya menjadi raja kerajaan Kediri menggantikan kakeknya Mpu Sendok. Raja Udayana memiliki tiga anak yaitu Airlangga, Marakarta dan Anak Wungsu.\n\nDari ke sepuluh candi diperkirakan candi yang berada pada sisi utara sungai dari lima candi di sisi timur sungai merupakan candi tertua. Hal ini dijelaskan dari tulisan Haji Lumah Ing Jalu dari aksara kwadrat pada gerbang candi. Tulisan ini memiliki arti “Sang raja dimakamkan di jalu (Sungai Tukad Pakerisan)” dari tulisan inilah diketahui bahwa candi ini merupakan tempat pemujaan arwah dari Raja Udayana. Keempat candi lain diperkirakan merupakan candi untuk permaisuri serta anak – anak dari Raja Udayana.",
            "Jl. Pos Sengi, Dukuhan, Ngampel, Kec. Dukun, Kab. Magelang, Jawa Tengah (56482).\n\nCandi Asu berlokasi di Lereng sebelah barat Gunung merapi tepatnya berada di tepian Sungai Tlingsing Pabelan, Dusun Candi Ps, Desa Sengi, Kecamatan Dukun, Kabupaten Magelang dengan koordinat 7°32′00″LS 110°21′00″BT atau berjarak sekitar 25 Km dari Candi Borobudur ke timur laut. Candi Asu merupakan peninggalan dari kerajaan Mataram Kuno dari trah Sanjaya (Mataram Hindu). Candi Asu berada tidak jauh dari jalur SBB atau Jalur Solo Selo Borobudur yang menjadi alternatif Magelang ke Solo melalui Taman Nasional Gunung Merapi.\n\nNama Candi Asu Sengi sendiri diambil dari penamaan masyarakat sekitar ketika candi ini pertama kali ditemukan. Nama asli dari candi ini belum diketahui kepastiannya. Nama Asu dalam Candi Asu Sengi diberikan karena pada awal penemuan candi ini terdapat sebuah patung Lembu Nandhi yang telah rusak dan lebih menyerupai asu atau anjing dalam bahasa Jawa, sedangkan kata sengi diambil dari nama desa dimana candi ini ditemukan. Sehingga masyarakat sekitar menyebut candi ini dengan nama Candi Asu Sengi.\n\nTerdapat tiga prasasti yang ditemukan di Candi Asu Sengi yaitu prasasti Sri Manggala II, Kurambitan I, dan Kurambitan II,. Dari ketiga prasati tersebut diperkirakan bahwa Candi Asu dibangun pada tahun 869 M saat Rakai Kayuwangi pada masa pemerintahan Wangsa Sanjaya berkuasa. Selain itu juga disebutkan bahwa candi ini merupakan tempat pemujaan, baik pemujaan terhadap dewa maupun arwah leluhur raja – raja yang telah meninggal. Selain itu juga terdapat relief kinara-kinari (burung) seperti yang ada di candi – candi lain seperti Candi Plaosan, Ratu Boko dan Candi Ijo.\n\nCandi Asu berbentuk bujur sangkar yaitu 7,94 meter kali 7,94 meter sedangkan tinggi candi adalah 2,5 meter dan tinggi tubuh candi adalah 3,35 meter dan menghadap barat. Candi Asu adalah candi sepotong karena tidak ditemukan bagian atap. Diperkirakan atap dari candi ini adalah kubah karena ditemukan banyaknya reruntuhan yang menggambarkan sebuah kubah pada sekitar candi dan sumur. Pada bagian dalam candi terdapat sebuah sumur yang memiliki kedalaman hingga 3 meter dan berbentuk bujursangkar dengan ukuran 1,3 meter kali 1,3 meter.",
            "Jl. Raya Piyungan - Prambanan No.2, Gatak, Bokoharjo, Kec. Prambanan, Kab. Sleman, Daerah Istimewa Yogyakarta (5572).\n\nPendirian Candi Ratu Boko bisa dilihat dari prasasti – prasasti yang ditemukan di sekitar Ratu Boko.Dahulu Ratu Boko adalah sebuah wihara bernama Abhayagiriwihara yang diperuntukkan para biksu. Abhayagiriwihara menurut prasasti Walaing didirikan pada 792 M. Kemudian pada 856 M komplek Ratu Boko dialih fungsikan sebagai kraton oleh Rakai Walaing Pu Khumbayoni yang beragama Hindu.\n\nRatu Boko memiliki dua unsur agama yaitu dari agama Hindu dan Budha. Unsur agama Hindu terlihat pada adanya yoni, arca ganesha dan durga, tiga miniatur candi, serta lempengan perak yang bertuliskan mantea agama Hindu. Sedangkan unsur Budha terlihat pada adanya arca buddha, reruntuhan stupa dan stupika.\n\nPenyebutan Ratu Boko sebagai kraton tertera dalam prasasti serta kemiripan struktur bangunan yang lebih menyerupai kraton dari pada candi. Dalam kitab – kitab kasusastraan tertera bahwa kraton adalah kompleks bangunan yang dikelilingi pagar bergapura, hal ini tertera di kasusastraan Bharatayudah, Kresnayana, Gatotkacasraya serta Bhomakawya.\n\nDi dalam kompleks Ratu Boko terdapat kolam serta bangunan – banguna lain. Dahulu bangunan Ratu Boko terbuat oleh kayu terlihat pada adanya umpak dan batur – batur di kompleks ini. Kraton Ratu Boko terbagi menjadi tiga bagian diantaranya, kelompok barat, tenggara dan timur. Bangunan – bangunan tersebut berupa teras – teras dan puncak bukit. Letak gerbang dari Ratu Boko terletak di bagian Barat yang memiliki pagar berupa batu andesit. Pada bagian tenggara terdapat struktur lantai, gapura, batur pendopo, batur pringgitan, miniatur candi, tembok keliling, dua kelompok kolam serta reruntuhan stupa. Terakhir pada bagian timur terdapat sebuah kolam dan dua buah gua yang bernama Gua Lanang dan Gua Wadon. Ratu Boko diperkirakan adalah istana yang dimaksud pada legenda Roro Jongrang.",
            "Dsn. Cepit - Bokoharjo, Kec. Prambanan, Kab. Sleman, Daerah Istimewa Yogyakarta (55572).\n\nCandi Banyunibo terletak di Komplek Ratu Boko yaitu di Dusun Cepit, Bokoharjo, Prambanan. Candi ini dibangun pada abad ke – 9, Candi Banyunibo terdiri dari satu candi induk dan enam candi perwara. Ukuran masing – masing stupa hampir memiliki ukuran yang sama yaitu 4,80 x 4,80 m. Pada sisi utara candi induk terdapat tembok yang membujur sepanjang 65 meter dari barat ke timur yang terbuat dari susunan batu. Dilihat dari bentuk atap candi baik induk maupun perwara menunjukkan bahwa candi ini adalah candi bercorak Buddha.\n\nUkuran candi induk yaitu 15,325 x 14,25 m dengan tinggi 14,25 m. Pintu candi berada di sebelah barat candi beserta tangga yang menghubungkan ke tubuh candi. Terdapat dinding penampil berupa relief di sebelah kanan dan kiri dinding candi, pada sebelah kanan candi menggambarkan relief seorang wanita yang dikerumuni anak – anak, sedangkan sebelah kiri terdapat relief seorang pria dalam posisi duduk. Kedua pahatan relief dinding tersebut menggambarkan Hariti, dewi kesuburan dan suaminya, Vaisaravana dalam ajaran agama Buddha. Pada dinding bagian luar candi terdapat sebuah arca Boddhisatva. Pada dinding bilik candi bagian utara, timur dan selatan terdapat relung yang menonjol keluar serta berbigkai kalamakara yang digunakan untuk menaruh arca.\n\nArti dari Banyunibo sendiri adalah air yang menetes. Candi ini berada di area persawahan dan rumpun pisang, serta terletak jauh dari candi – candi Buddha lain. Pada Candi Banyunibo terdapat unsur Hindu yaitu adanya arca nandi yang terdapat di sepanjang jalan menuju pos penjagaan. Candi ini merupakan rangkaian dari komplek Ratu Boko. Atap candi induk memiliki ukuran tinggi 2,75 m dengan stupa dengan tinggi 3,5 m.\n\nPenelitian tentang Candi Banyunibo dilakukan sejak tahun 1940, rekonstruksi candi ini dilakukan pada tahun 1943. Pemugaran pertama Candi Banyunibo menghasilkan bagian alas, kaki candi, tubuh candi serta pagar yang terletak di sisi utara Candi Banyunibo.",
            "Jl. Raya Ngetos, Selopuro, Ngetos, Kec. Ngetos, Kab. Nganjuk, Jawa Timur (64474).\n\nCandi Ngetos terletak di Desa Ngetos, Kecamatan Ngetos, Kabupaten Nganjuk, Jawa Timur. Candi ini dikenal sebagai candi perabuan dari Prabu Hayam Wuruk. Pada papan keterangan menyebutkan Candi Ngetos dibangun pada abad ke 15. Secara fisik Candi Negtos dalam keadaan rusak pada beberapa bagian bahkan pada beberapa bagian telah hilang sehingga sulit memperkirakan bentuk aslinya.\n\nDi Candi Ngetos pernah ditemukan arca Siwa dan Wisnu. Hl ini kemudian menimbulkan asumsi bahwa candi ini beraliran Siwa Wisnu. Asumsi tersebut diperkuat dengan aliran agama Siwa yang dianut oleh Hayam Wuruk. N.J. Krom memperkirakan bahwa Candi Ngetos semula dikelilingi tembok yang berbentuk cincin. Bangunan utama candi terbuat dari batu bata merah dan atapnya diperkirakan terbuat dari kayu (kini sudah tidak ada bekasnya). Candi Ngetos berukuran panjang 9,1 m, tinggi badan 5,43 m, dan tinggi keseluruhan 10 m.\n\nTerdapat empat buah relief di Candi Ngetos, namun karena faktor usia relief tersebut hanya terisa satu dan tiga lainnya telah ancur. Tidak hanya relief yang hilang melainkan pigura – pigura pada alasnya yang juga telah tidak ada lagi. Pada bagian atas dan bawah pigura, dibatasi oleh loteng – loteng yang terbagi dalam cendela – cendela kecil berhiaskan ketupat yang tepinya tidak rata atau menyerupai bentuk banji. Hal tersebut berbeda dengan bangunan bawahnya yang tidak ada piguranya, sedangkan tepi bawahnya dihiasi dengan motif kelompok buah dan ornamen daun.\n\nPada sisi kiri dan kanan candi terdapat dua relung kecil. Diatasnya terdapat ornamen yang mirip dengan belalai makara. Namun jika diperhatikan ternyata belalai tersebut adalah bentuk spiral yang diperindah. Dinding candi ini kosong dan hanya terdapat motif daun yang melengkung ke bawah dan horizontal melingkari tubuh candi bagian atas. Ada hal menarik dari kala yang terlihat sangat besar dengan ukuran tinggi 2 m dan lebar 1,8 m. Kala tersebut masih utuh dengan wajah menakutkan.",
            "Desa. Sukomulyo, Gadungan, Gandusari, Blitar Regency, East Java (66187).\n\nCandi Wringin Branjang terletak di Bukit Gedang, Dusun Sukomulyo, Desa Gadungan, Kecamatan Gandusari. Candi ini memiliki bentuk yang unik yang mirip dengan rumah atau pos jaga. Bentuk dari candi ini adalah persegi pada tubuh candi dan limas pada atap candi, pintu candi menghadap ke arah selatan.  Pada sisi – sisi dinding candi terdapat semacam lubang ventilasi yang berbentuk bintang. Candi ini memiliki panjang 400 cm, lebar 300 cm serta tinggi 500 cm. Dibangun pada masa pemerintahan Raden Wijaya dengan adanya bukti yaitu pahatan angka bertahun 1231 Saka atau 1309 Masehi yang dipahatkan pada balok batu pada situs gadungan yang berada sekitar 100 m dari Candi Wringin Branjang. Diperkirakan candi ini digunakan sebagai tempat pemujaan.\n\nArsitektur candi dibagi menjadi dua yaitu atap dan badan candi, dan tidak memiliki kaki candi layaknya candi – candi lain. Menurut juru kunci dari Candi Wringin Branjang, sebenarnya candi ini memiliki kaki candi, namun masih terpendam di dalam tanah. Candi Wringin Branjang belum sekalipun di pugar. Hingga saat ini belum ditemukan adanya keterkaitan candi ini dengan kerajaan yang ada di wilayah di Jawa Timur, namun pada kegiatan penggalian yang dilakukan pada tahun 1915 ditemukan adanya arca Dewi Sri dalam keadaan patah menjadi dua bagian. Dengan adanya temuan tersebut dapat diperkirakan bahwa candi ini adalah candi Hindu.",
            "Jl. Panggung, Kidal, Kec. Tumpang, Kab. Malang, Jawa Timur (65156).\n\nCandi Kidal berada di Desa Rejokidal, Kecamatan Tumpang, Kabupaten Malang. Candi Kidal oleh masyarakat sekitar dianggap sebagai candi pemujaan yang berumur paling tua di wilayah Jawa Timur. Candi ini didirikan pada 1248 M setelah upacara pemakaman Cradha untuk Raja Anusapati dari Kerajaan Singasari. Dibangunnya Candi Kidal bertujuan untuk mendarmakan Raja Anusapati agar dapat mendapatkan kemuliaan sebagai Syiwa Mahadewa. Dibangunnya candi ini yaitu berdekatan dengan masa transisi kejayaan kerajaan di Jawa Tengah yang berpindah ke Jawa Timur sehingga pada struktur candi ini masih ditemukan unsur – unsur perpaduan candi bercorak Jawa Tengah dan Jawa Timur. Sebagian pendapat para ahli menganggap candi ini merupakan prototype atau versi beta dari candi Jawa Timuran.\n\nStruktur Candi Kidal terbuat dari batu andesit dan berbentuk geometri vertikal. Terdapat pagar berupa batu yang berada di pelataran candi. Badan candi berdiri pada batur setinggi 2 m. Terdapat tangga untuk mencapai selasar candi. Tangga ini dilengkapi dengan pipi tangga dengan bentuk ukel layaknya tangga – tangga di candi lain namun perbedaannya pada anak tangga pertama terdapat badug (tembok rendah) disisi kiri dan kanan yang berbentuk siku yang menutup samping serta sebagian sisi depan kaki tangga. Badug yang ada di Candi Kidal tidak ditemukan di candi – candi lain.\n\nCandi Kidal menghadap ke barat dengan pintu yang dilengkapi kalamakara yang berada pada ambang pintu. Atap Candi Kidal bersusun tiga dengan bentuk semakin keatas semakin kecil dengan bagian paling atas berbentuk persegi. Pada tepi tepi atap candi terdapat hiasan berupa ukiran bungan dan sulur – suluran. Pada kaki candi terdapat hiasan pahatan dengan motif medalion yang berjajar diselingi bingkai dengan motif bunga serta sulur – suluran. Pada pangkal candi terdapat arca berbentuk singa dengan satu kaki terangkat ke atas layaknya sedang mengangkat pelipit atas kaki candi.\n\nTubuh candi ini terbilang ramping bila dibandingkan dengan bagian kaki candi. Ruangan dalam candi juga terhitung sempit. Ruangan ini dalam keadaan kosong sekarang. Pada dinding candi terdapat hiasan pahatan dengan motif medalion. Dinding samping dan belakang terdapat tempat untuk meletakkan arca. Relung – relung arca tersebut terdapat kalamakara diatasnya. Saat ini tidak ada satupun arca yang tersisa di Candi Kidal. Konon arca Syiwa yang indah di Museum Leiden berasal dari Candi Kidal ini.",
            "Desa. Jatipasar, Kec. Trowulan, Kab. Mojokerto, Jawa Timur (61362).\n\nCandi Wringin Lawang terletak di Dukuh Wringin Lawang, Desa Jati Pasar, Kecamatan Trowulan, Kabupaten Mojokerto. Candi atau Gapura Wringin Lawang adalah bangunan kuno berupa Gapura Belah tanpa atap atau disebut tipe candi bentar. Gapura ini diperkirakan merupakan gerbang masuk ke Kerajaan Majapahit yang disusun dari batu bata merah yang pada perkembangannya gerbang ini kemudian diduplikat provinsi Jawa Timur sebagai gerbang masuk.\n\nKata wringin lawang diambil dari bentuk pintu (lawang) dan di dekat bangunan tersebut terdapat pohon beringin yang mengapit Gapura Wringin Lawang. Bahan Candi Wringin Lawang terbuat dari batu bata merah tanpa adanya hiasan. Bentuk dari bangunan ini adalah candi yang terbelah menjadi dua dan kemudian di renggangkan dan bagian atap candi tidak tertutup. Bentuk seperti ini disebut “Candi Bentar” atau “Gapura Gapit” atau bisa juga disebut “Gapura Belah”.\n\nTinggi dari bangunan ini adalah 13,70 meter dan dengan ukuran 13×11,5 meter dan dengan tinggi 15,5 meter. Beberapa bagian tertentu telah dikonsolidasi atau tambal sulam dengan batu bata yang serupa. Bangunan ini berdiri di tanah seluas 616 m2. Orang – orang menyebut Gerbang Wringin Lawang adalah gapura masuk ke Kerajaan Majapahit yang ada di sebelah utara Candi Wringin Lawang. Jadi bisa disimpulkan bahwa ambang candi ini menghadap ke utara dan selatan. Sedangkan arah hadap Candi Wringin Lawang menghadap ke timur dan barat. Bangunan ini belum bisa disebut sebagai gapura utama ke Majapahit, sebab pintu gerbang istana Kerajaan Majapahit berpagar besi serta kereta dapat masuk ke dalamnya.",
            "Dsn. Candirejo, Tegowangi, Kec. Plemahan, Kabupaten Kediri, Jawa Timur (64155).\n\nCandi Tegawangi terletak di Desa Tegowangi, Kecamatan Plemahan, Kabupaten Kediri, berjarak 24 km dari Kota Kediri. Letaknya berada di perumahan pendiduk berjarak 1 km dari jalan raya, lingkungan candi sudah tertata rapi oleh pemerintah. Candi ini diperkirakan berdiri pada abad ke 14 atas perintah dari Hayam Wuruk. Dibangunnya Candi Tegawangi bertujuan untuk meruwat atau menghilangkan keburukan dari Bhre Metahun, sepupu Hayam Wuruk. Kata tegawangi tercatat di Kitab Pararaton yang menyebutkan Bhre Metahun meninggal pada 1310 saka atau tahun 1388 Masehi kemudian didarmakan di Tegawangi.\n\nCandi ini berdenah bujur sangkar dengan menghadap ke arah barat dengan luas 11,20 m serta dengan tinggi sekitar 4,29. Candi ini terbuat dari batu andesit yang ukurannya lebih besar dibandingkan dengan Candi Surawana yang juga terdapat di Kediri. Candi ini dalam keadaan rusak dan hanya tersisa sebagian kecil dari tubuh candi.\n\nPada tangga candi terdapat relief yang menggambarkan pemain genderang. Pada kaki candi terdapat relief dengan motif sulur, bunga serta gana yang tersusun secara berselang seling. Pada dinding candi terdapat relief yang sangat halus pahatannya, yang menceritakan Kidung Sudamala. Relief Kidung Sudamala ini memperkuat dugaan bahwa Candi Tegawangi merupakan candi untuk pengruwatan. Selain di Candi Tegawang, cerita Sudamala juga terdapat di Candi Sukuh. Pada sudut tenggara halaman terdapat jajaran batu reruntuhan candi yang belum bisa diidentifikasi dan dibangun kembali. Selain itu juga terdapat beberapa arca termasuk arca Parwati.",
            "Jl. Argomulyo, Cangkringan, Sleman, Daerah Istimewa Yogyakarta.\n\nCandi Morangan terletak di kaki gunung merapi tepatnya Dusun Morangan, Sindumartani, Ngemplak, Kabupaten Sleman, Yogyakarta. Candi ini merupakan candi Hindu yang dibangun pada abad ke 9 dan 10 M pada masa Kerajaan Mataram Kuno. Bangunan Candi Morangan terdiri dari candi induk dan candi perwara yang masing – masing terbuat dari batu andesit. Candi Morangan dalam keadaan terpendam pada saat pertama kali ditemukan pada tahun 1982 yaitu pada kedalaman 6,5 meter dibawah permukaan tanah. Terdapat relief pada bagian batang kaki, batang tubuh candi yang terletak diantara perbingkaian atas dan perbingkaian bawah.\n\nCandi perwara menghadap ke arah timur dengan ukuran 4 x 4. Candi Morangan memiliki ciri khas dimana terdapat panel relief yang merupakan bagian dari cerita Tantri Kamandaka tentang seekor harimau yang tertipu oleh seekor kambing. Cerita tersebut hanya ada dalam candi Buddha.  Terdapat arca yoni dan arca resi didalam relung – relung candi. Candi induk sendiri menghadap ke barat, memiliki 1 bilik dan berdenah bujur sangkar dengan ukuran 7,95 m x 7,95 m. Candi Morangan juga memiliki selasar dengan lebar 90 m. Profil candi ini terdiri atas sisi genteng belah rotan, bingkai persegi, serta takuk ganda. Candi Morangan berlokasi dekat dengan Kali Gendol yang sangat rawan akan adanya sapuan banjir lahar dingin.",
            "Desa. Bugisan, Kec. Prambanan, Kab. Klaten, Jawa Tengah.\n\nCandi Bubrah juga masih masuk Kawasan Prambanan. Candi Bubrah yang terbuat dari batu andesit, berdenah persegi panjang, dan berukuran 12×12 meter itu sudah sangat rusak saat ditemukan. Candi hanya tersisa reruntuhan setinggi dua meter. Itu sebabnya masyarakat menyebutnya sebagai Candi Bubrah. Pendirian Candi Bubrah diyakini semasa dengan Candi Sewu dan Candi Lumbung, ketiganya menjadi satu kesatuan mandala bercorak Budhist. Komplek tempat pemujaan ini dibangun Rakai Panangkaran yang disebut sebagai Syailendra Wangsa Tilaka, atau mutiara keluarga Syailendra.\n\nRakai Panangkaran adalah pemimpin dinasti Syailendra yang berpindah agama, dari semula Siwa (Hindu). Ia diperintahkan ayahandanya untuk menjadi Budha, dan ia memang jadi seorang Budhist yang amat taat. Rakai Panangkaran pula yang membangun Candi Kalasan, persembahan untuk Dewi Tara. Selain itu pula dibangun Candi Sari dan Candi Sewu. Namun saat semua bangunan suci itu paripurna, Rakai Panangkaran sudah wafat. Peresmian dilakukan penggantinya, Rakai Panaraban. Candi Bubrah merupakan bangunan tunggal menghadap ke timur, sama halnya dengan komplek Candi Prambanan yang juga menghadap ke timur.\n\nBangunan terkesan tinggi ramping dengan atap stupa menjadi simbol Gunung Meru. Susunan stupa induk merujuk konsep pantheon dalam agama Budha. Satu stupa dikelilingi delapan stupa, kemudian dikelilingi 16 stupa. Bagian luar tubuh candi ada relung-relung berisi arca Dhyani Buddha. Relung utara  berisi Dhyani Buddha Amogasiddhi menghadap utara. Relung barat Dhyani Buddha Amitabha. Relung selatan berisi arca Dhyani Buddha Ratnasambhawa. Sedangkan sisi timur relungnya berisi arca Dhyani Buddha Aksobhya. Perbedaan di antara arca Dhyani Buddha itu ada salah satunya pada posisi duduk dan tangannya. Candi Bubrah seperti dikutip dari laporan Purna Pugar Candi Bubrah terbitan BPCB Jateng, memiliki keunikan yang tidak dimiliki candi-candi Buddha lainnya. Antara lain, motif hiasan taman teratai yang mengisi lapik di bawah padmasina pada Dhyani Buddha.",
            "Desa. Bugisan, Kec. Prambanan, Kab. Klaten, Jawa Tengah.\n\nCandhi Sewu adalah candi Buddha yang dibangun pada abad ke-8 Masehi yang berjarak sekitar delapan ratus meter di sebelah utara Candi Prambanan. Candi Sewu merupakan kompleks candi Buddha terbesar kedua setelah Candi Borobudur di Jawa Tengah. Dikenal dengan nama asli Manjusrigrha, Candi Sewu berusia lebih tua daripada Candi Borobudur dan Prambanan. Meskipun aslinya memiliki 249 candi, oleh masyarakat setempat candi ini dinamakan (Sewu) yang berarti seribu dalam bahasa Jawa. Penamaan ini berdasarkan kisah legenda Loro Jonggrang.\n\nBerdasarkan Prasasti Kelurak yang berangka tahun 782 dan Prasasti Manjusrigrha yang berangka tahun 792 dan ditemukan pada tahun 1960, nama asli candi ini adalah ”Prasada Vajrasana Manjusrigrha”. Istilah Prasada bermakna candi atau kuil, sementara Vajrajasana bermakna tempat Wajra (intan atau halilintar) bertakhta, sedangkan Manjusri-grha bermakna Rumah Manjusri. Manjusri adalah salah satu Boddhisatwa dalam ajaran buddha. Candi Sewu diperkirakan dibangun pada abad ke-8 masehi pada akhir masa pemerintahan Rakai Panangkaran. Rakai Panangkaran (746–784) adalah raja yang termahsyur dari kerajaan Mataram Kuno.\n\nKompleks candi ini mungkin dipugar, dan diperluas pada masa pemerintahan Rakai Pikatan, seorang pangeran dari dinasti Sanjaya yang menikahi Pramodhawardhani dari dinasti Sailendra. Setelah dinasti Sanjaya berkuasa rakyatnya tetap menganut agama sebelumnya. Adanya candi Sewu yang bercorak buddha berdampingan dengan candi Prambanan yang bercorak hindu menunjukkan bahwa sejak zaman dahulu di Jawa umat Hindu dan Buddha hidup secara harmonis dan adanya toleransi beragama. Karena keagungan dan luasnya kompleks candi ini, candi Sewu diduga merupakan Candi Buddha Kerajaan, sekaligus pusat kegiatan agama buddha yang penting pada masa lalu. Candi ini terletak di lembah Prambanan yang membentang dari lereng selatan Gunung Merapi di utara hingga pegunungan Sewu di selatan, di sekitar perbatasan Yogyakarta dengan Kabupaten Klaten, Jawa Tengah.",
            "Desa Ngawen, Kec. Muntilan, Kab. Magelang.\n\nCandi Ngawen adalah candi bercorak Buddhisme yang berada kira-kira 5 km sebelah selatan candi Mendut, Bukti Candi Ngawen berlatar belakang agama Budha berupa temuan arca Dhyani Buddha Ratnasambhawa di Candi II dan arca Dhyani Buddha Amithaba di Candi IV. Berdasarkan gaya arsitektur bangunannya, situs candi di Kabupaten Magelang ini berdiri sekitar abad IX – X Masehi.\n\nBentuk bangunannya memiliki ciri khas yang menjadi pembeda dengan candi lainnya. Yaitu dengan adanya hiasan patung singa pada keempat sudutnya. Sepintas nyaris mirip dengan bangunan candi Hindu karena bentuknya yang meruncing. Akan tetapi, jika kalian amati dengan saksama, candi ini memiliki stupa dan teras (undak-undak) yang menjadi simbol dalam candi-candi Buddha.Menurut perkiraan, candi ini dibangun oleh penguasa Kerajaan Mataram Kuno dari wangsa Sailendra pada abad ke-8. Menurut Soekmono keberadaan candi Ngawen ini kemungkinan besar adalah bangunan suci yang tersebut dalam prasasti Karang Tengah pada tahun 824 M, yaitu Venuvana (Sanskerta, yang berarti (hutan bambu). Candi ini terdiri dari lima bangunan candi yang berukuran kecil, dua di antaranya mempunyai bentuk yang berbeda dengan dihiasi oleh patung singa pada keempat sudutnya. Sebentuk patung Buddha yang sudah tidak berkepala dengan posisi duduk Ratnasambawa tampak berada pada salah satu candi lainnya. Beberapa relief pada sisi candi masih tampak cukup jelas, di antaranya adalah ukiran Kinnara, Kinnari, dan kala-makara. Posisi hiasan Kinnara Kinnari mengapit Kalpataru. Kinnara dan Kinnari menggambarkan mahkluk kahyangan yang berwujud setengah manusia dan setengah burung. Sementara itu, Kalpataru merupakan pohon kahyangan yang hidup sepanjang masa tempat dimana menggantungkan segala asa. Pohon ini digambarkan memiliki dahan-dahan yang diartikan sebagai untaian perhiasan yang indah, sehingga dijaga makhluk-makhluk kahyangan seperti Kinara Kinari.",

    };

    private static final int[] imageCandi = {
            R.drawable.singosari,
            R.drawable.gambarwetan,
            R.drawable.penataran,
            R.drawable.borobudur,
            R.drawable.prambanan1,
            R.drawable.dieng,
            R.drawable.badut,
            R.drawable.lumbung,
            R.drawable.gedongsongo,
            R.drawable.simping,
            R.drawable.jawi,
            R.drawable.mendut,
            R.drawable.sojiwan,
            R.drawable.jabung,
            R.drawable.cangkuang1,
            R.drawable.bajangratu,
            R.drawable.belahan,
            R.drawable.gununggangsir,
            R.drawable.goagajah,
            R.drawable.pari,
            R.drawable.surowono,
            R.drawable.candiplaosan,
            R.drawable.sukuh,
            R.drawable.selogriyo,
            R.drawable.tebing,
            R.drawable.asusengi,
            R.drawable.ratuboko,
            R.drawable.banyunibo,
            R.drawable.ngetos,
            R.drawable.wringinbranjang,
            R.drawable.candikidal,
            R.drawable.wringinlawang,
            R.drawable.tegowangi,
            R.drawable.morangan,
            R.drawable.bubrah,
            R.drawable.sewu,
            R.drawable.ngawen,

    };

    static ArrayList<Candi> getListData(){
        ArrayList<Candi> list = new ArrayList<>();
        for (int position = 0; position < urutanCandi.length; position++){
            Candi candi = new Candi();
            candi.setNama(urutanCandi[position]);
            candi.setDetail(detailCandi[position]);
            candi.setPhoto(imageCandi[position]);
            list.add(candi);
        }
        return list;
    }
}

