package com.virnanda.candiindonesia;

import java.util.ArrayList;

public class DataCandi {
    private static final String[] urutanCandi = {
            "Candi Singosari",
            "Candi Gambar Wetan",
            "Candi Penataran",
            "Candi Borobudur",
            "Candi Prambanan",
            "Candi Dieng",
            "Candi Badut",
            "Candi Lumbung",
            "Candi Gedong Songo",
            "Candi Simping",
            "Candi Jawi",
            "Candi Mendut",
            "Candi Sojiwan",
            "Candi Jabung",
            "Candi Cangkuang"

    };

    private static String detailCandi[] = {
            "Singosari Malang - Jawa Timur\n\nCandi ini terletak di Desa Candi Renggo, Kecamatan Singosari, Kabupaten Malang dengan jarak kurang lebih sekitar 9 km dari kota Malang ke arah Surabaya. Nama lain candi ini adalah Candi Cungkup atau Candi Menara, nama yang menunjukkan bahwa Candi Singasari merupakan candi tertinggi yang ada di sekitarnya. Akan tetapi di sekitar Kecamatan Singasari hanya Candi Singari lah yang masih tersisa dan yang lein telah lenyap.\n\nPara ahli purbakala memperkirakan bahwa Candi Singasari dibangun pada 1300 M, sebagai penghormatan kepada Raja Kertanegara. Terdapat dua candi yang digunakan untuk penghormatan yaitu Candi Jawi dan Candi Singasari.Candi Singasari merupakan candi beraliran syiwa. Hal ini terlihat pada beberapa arca Syiwa yang ada di halaman candi.",
            "Blitar - Jawa Timur\n\nCandi Gambar Wetan terletak lereng Gunung Kelud tepatnya di Perkebunan Gambar, Desa Sumberasri, Kecamatan Nglegok, Kabupaten Blitar, Jawa Timur. Candi Gambar Wetan dalam keadaan tidak utuh. Yang tersisa hanyalah batur candi dengan relief yang masih tersisa. Bagian lain dari komponen areal ini adalah dwarapala yang berjumlah dua buah yang menjaga tangga masuk menuju candi.\n\nCandi Gambar Wetan terletak di puncak bukit dengan dwarapala yang menjaga pada tangganya. Candi ini diperkirakan berasal dari masa Kerajaan Majapahit. Candi Gambar Wetan dipercaya merupakan tempat peristirahatan Hayam Wuruk dan raja Majapahit lain dalam perjalanannya menuju Gunung Kelud ataupun Candi Penataran.\n\nKetika ditemukan pertama kali oleh petugas perkebunan, cangkul petugas perkebunan mengenai sisi candi dan ditemukan arca. Selanjutnya dilakukan penggalian pada tahun 1992. Kata petugas, di candi ini pernah ditemukan relief Werkudara di Dam Sangiran. Namun sebelum candi ini diresmikan oleh pemerintah, banyak terjadi penjarahan oleh warga yang mengambil relief dari Candi Gambar Wetan. Pada zaman penjajahan Belanda, relief candi banyak diambil guna dijadikan pajangan di rumah Direksi Kebesaran. Namun kini patung relief telah diambil alih pemerintah serta diamankan ke museum dan dimasukkan ke Trowulan.",
            "Blitar - Jawa Timur\n\nCandi Penataran merupakan salah satu candi di Blitar dengan corak relief, arca dan struktur bergaya Hindu. Candi Penataran berlokasi di Desa Penataran, Kecamatan Nglegok, Kota Blitar, Provinsi Jawa Timur. Bukti bahwa candi ini bercorak Hindu adalah adanya pahatan Kala (raksasa menyeringai), Patung Dwarapala (Raksasa penjaga pintu gerbang), arca Ganesha (perlambang dewa ilmu pengetahuan dalam mitologi Hindu), dan relief Ramayana. Selain bernama Candi Penataran atau Panataran, beberapa ahli menganggap bahwa candi ini bernama Candi Palah.\n\nCandi Penataran dibangun pada tahun 1194 yang tergambar pada Prasasti Palah yang ada di area Candi Penataran yang menyebutkan bahwa candi ini mulai dibangun pada pemerintahan raja Syrenggra Kerajaan Kediri dan selesai pada masa pemerintahan Majapahit. Dengan begitu dapat dikatakan bahwa kerajaan ini dibangun pada tiga masa yaitu masa Kerajaan Kediri, masa Kerajaan Singosari, dan masa Kerajaan Majapahit. Candi ini memiliki peran penting dalam ketiga kerajaan tersebut yaitu sebagai tempat pengangkatan raja serta sebagai tempat diadakannya upacara pemujaan bagi Sang Pencipta.",
            "Magelang - Jawa Tengah\n\nCandi Borobudur terletak di Kabupaten Magelang, berjarak 15 km dari Yogyakarta. Borobudur terletak di bukit Menoreh serta dikelilingi oleh gunung – gunung besar seperti Merbabu, Merapi, Sindoro dan Sumbing. Candi ini pun dekat dengan Candi Mendut yaitu berjarak 3 km. Borobudur merupakan peninggalan Dinasti Syailendra dari abad ke – 9 M. Selain nama Borobudur juga disebut Barabudhur dalam sejarahnya.\n\nBerdasarkan perbandingan analisa antara aksara yang ada di Karmawibhangga dan jenis aksara yang lazim digunakan pada abad ke 8 hingga ke 9 Masehi, diperkirakan candi ini dibangun pada sekitar tahun 800 masehi. Hal ini termasuk dalam kurun waktu kejayaan pemerintahan wangsa Syailendra yaitu pada 760 M hingga 830 Masehi. Pembangunan Candi Borobudur baru terselesaikan pada masa pemerintahan Raja Samaratungga yaitu sekitar tahun 825 Masehi. Belum terlalu jelas mengenai bukti peninggalan sejarah dari Borobudur dan hanya beberapa prasasti saja yang menyinggung mengenai keberadaan Candi Borobudur. Borobudur diduga dirancang oleh seorang arsitek terkenal pada masa lalu yaitu yang bernama Gunadharma. Dan diperkirakan pembangunan Candi Borobudur selesai saat Dinasti Syailendra dengan raja pada masa pemerintahan Raja Samaratungga.",
            "Klaten - Jawa Tengah\n\nCandi Prambanan merupakan candi Hindu terbesar di Indonesia yang terletak di Desa Bokoharjo, Kecamatan Prambanan, Kabupaten Sleman, Yogyakarta. Uniknya, pintu gerbang dari candi ini terletak di provinsi yang berbeda yakni Desa Tlogo, Kecamatan Prambanan, Klaten, Jawa Tengah. Lokasi dari candi ini tak jauh dari jalan raya, hanya sekitar 100 meter dari jalan raya Solo – Yogya. Candi Prambanan belum diketahui secara pasti kapan dibangunnya, sebagian ahli menduga bahwa Candi Prambanan dibangun pada pertengahan abad ke – 9 oleh Wangsa Sanjaya tepatnya pada pemerintahan Raja Bitung Maha Sambu. Hal ini diceritakan oleh Prasasti Syiwargha yang ditemukan di sekitar Candi Prambanan yang sekarang tersimpan di Taman Nasional di Jakarta. Prasasti ini menerangkan pembangunan Candi Prambanan adalah tahun 788 Saka atau 856 Masehi dan ditulis pada masa pemerintahan Rakai Pikatan.\n\nProses pemugaran candi memakan waktu yang panjang seiring waktu ditemukan candi – candi di sekitar bangunan utama Candi Prambanan. Bangunan terbesar yaitu Candi Syiwa dilaporkan oleh C.A. Lons pada tahun 1733 dan kemudian dilakukan penggalian dan pencatatatan oleh Groneman dan selanjutnya diselesaikan pada tahun 1885. Upaya tersebut meliputi pembersihan semak belukar dan mengelompokkan batu – batu reruntuhan candi. Pada tahun 1902 van Erp melanjutkan upaya pengelompokan batu – batu Candi Prambanan lebih rinci. Pada tahun 1918 dilakukan kembali pemugaran oleh Dinas Purbakala Belanda (Oudheikundige Dienst) dengan merekonstruksi bangunan Candi Syiwa dibawah pimpinan P.J. Perquin.",
            "Wonosobo - Jawa Tengah\n\nCandi Dieng merupakan sebuah kompleks Candi yang berada di dataran tinggi dieng yang berada pada ketinggian 2000 meter diatas permukaan laut. Kompleks Candi ini juga merupakan salah satu candi tertua di Jawa yang dibangun sekitar abad ke 7 hingga abad ke-9 Masehi. Area kompleks candi ini juga memiliki wilayah yang cukup luas, memiliki panjang hampir 1900 meter dan lebar sekitar 800 meter. Candi Dieng merupakan candi peninggalan agama hindu yang beraliran syiwa, diperkirakan dibangun pada masa pemerintahan kerajaan Kalingga pada masa dinasti Wangsa Sanjaya.\nCandi dieng terdiri dari delapan candi yang berukuran kecil. Hingga saat ini, nama candi dan sejarah berdirinya candi-candi di Dieng masih menjadi misteri, karena minimnya sumber dan masih sedikitnya penemuan prasasti-prasasti yang mengungkap sejarah di balik berdirinya candi tersebut. Namun, masyarakat lokal menamainya dengan tokoh-tokoh pewayangan yang terkenal, seperti Arjuna, Gatutkaca, Dwarawati, dan Bima. Sejarah Candi Dieng diawali dengan penemuan sebuah prasasti yang berangka tahun 808. Prasasti tersebut merupakan prasasti tertua dengan tulisan Jawa Kuno. Jadi para ilmuwan menyimpulkan Candi Dieng dibangun pada pemerintahan raja-raja Wangsa Sanjaya. Di kawasan candi dieng juga ditemukan arca dewa Syiwa yang saat ini di simpan di Museum Nasional Jakarta.",
            "Malang - Jawa Timur\n\nCandi Badhut terletak di Desa Karangbesuki, Kecamatan Dau, Kabupaten Malang, Jawa Timur. Candi ini ditemukan pada tahun 1923 oleh pakar arkeologi. Diperkirakan candi ini dibangun jauh sebelum pemerintahan Airlangga, yaitu masa awal pembangunan candi – candi yang ada di Jawa Timur serta diduga merupakan candi tertua di Jawa Timur. \n\nSebagian ahli purbakala mengatakan bahwa candi ini dibangun atas perintah dari Raja Kanjuruhan bernama Raja Gajayana. Pada Prasasti Dinoyo yang berangka tahun 682 saka atau 760 masehi yang ditemukan di Desa Merjosari, Malang menyebutkan bahwa pusat dari Kerajaan Kanjuruhan adalah daerah Dinoyo.\n\nPrasasti Dinoyo kini tersimpan di Museum Nasional Jakarta. Tulisan dalam prasasti ini menyebutkan bahwa masa keemasan Kerajaan Kanjuruhan adalah pada masa pemerintahan Raja Dewasimba dan putranya yang bernama Sang Liswa. Keduanya dalam memimpin kerajaan sangat adil dan bijaksana. Konon Raja Sang Liswa merupakan raja yang senang melucu atau dalam bahasa Jawa disebut mbadut, sehingga candi yang Sang Liswa bangun dinamakan Candi Badhut. Walaupun demikian hingga saat ini belum ditemukan bukti adanya hubungan dengan Raja Gajayana.",
            "Sleman - Yogyakarta\n\nCandi Lumbung merupakan candi yang terletak di kawasan Prambanan, tepatnya di Dukuh Bener, Desa Bugisan, Kecamatan Prambanan, Kabupaten Klaten, Jawa Tengah. Candi ini merupakan salah satu candi yang masuk dalam Kawasan Warisan Dunia Prambanan. Candi Lumbung merupakan candi Buddha yang diperkirakan dibuat di sekitar abad ke-9 sampai abad ke-10, tepatnya pada saat masih dikuasai oleh kerajaan Mataram Kuno. Candi Lumbung adalah candi yang tak jauh berbeda ataupun berhubungan dengan Candi Sewu. Hal ini diketahui dari bentuk candi-candi perwaranya yang mirip dengan candi perwara di Sewu yaitu atapnya yang berbentuk stupa. Hal ini juga menunjukan bahwa Candi Lumbung berlatar belakang candi Buddha. Nama Lumbung sendiri masih belum jelas diketahui secara pasti. Nama tersebut merupakan sebutan masyarakat di sekitarnya karena bentuknya yang mirip lumbung (bangunan tempat penyimpanan padi). Di dekat Candi Lumbung pernah ditemukan prasasti yang dikenal dengan Prasasti Kelurak.\nMenurut Boechari, seorang ahli epigrafi, prasasti ini berhubungan dengan pendirian Candi Sewu, mengingat adanya pendirian kirtistambha untuk Dewa Manjusri yang merupakan Dewa utama di Candi Sewu. Candi Lumbung belum diketahui, apakah didirikan oleh Sri Maharaja Rakai Panangkaran seperti halnya Candi Sewu, belum dapat dijelaskan. Keadaan batu pada Prasasti Kelurak sudah sangat aus atau sudah sulit untuk dibaca, sehingga isi keseluruhannya kurang diketahui. Namun, secara garis besar prasasti Kelurak ini berisi tentang didirikannya sebuah bangunan suci untuk arca Manjusri atas perintah Raja Indra yang bergelar Sri Sanggramadhananjaya. Menurut para ahli, yang dimaksud dengan bangunan tersebut adalah Candi Sewu, yang terletak di Kompleks Percandian Prambanan. Nama raja Indra tersebut juga ditemukan pada Prasasti Ligor dan Prasasti Nalanda peninggalan kerajaan Sriwijaya. Prasasti ini kini disimpan dengan No. D.44 di Museum Nasional, Jakarta.",
            "Bandungan - Jawa Tengah\n\nSejarah Candi Gedong Songo merupakan beberapa candi yang berkelompok hingga membentuk sebuah komplek percandian yang merupakan salah satu peninggalan agama Hindu. Lokasi candi ini di desa Candi, kecamatan Bandungan, Jawa Tengah. Secara geografis, letak candi ini berada di koordinat -7.210290, +110.342010, yang berada di ketinggian 1200 m di atas permukaan laut. Lokasi tepatnya di kaki Gunung Ungaran sehingga kesejukkan dapat dirasakan di area ini. Suhunya pun sekitar 19° – 27° Celcius. Letaknya 15 km dari kota Ambarawa dan 45 km dari kota Semarang. Candi Gedong Songo belum diketahui kapan dibangunnya candi ini hingga sekarang, bahkan para arkeolog pun belum bisa memecahkan problem ini. Sehingga candi ini sampai sekarang masih sering dijadikan sebagai bahan penelitian di bidang arkeologi. Namun, ada beberapa yang berpendapat bahwa candi ini dibangun di masa pemerintahan dinasti Sanjaya Hindu di Jawa yaitu sekitar abad ke-8. Hal ini pun ditinjau dari segi bangunannya dan coraknya.\nBentuk dan relief itu telah dijadikan bukti bahwa candi ini dibangun di masa pemerintahan dinasti Sanjaya. Hal inilah yang menguatkan mereka berpendapat bahwa candi ini di bangun pada abad ke-8. Namun, belum ada yang memastikan bahkan tahun pembangunan candi ini pun belum dikonvensionalkan oleh beberapa ahli.",
            "Blitar - Jawa Timur\n\nCandi Simping atau masyarakat sekitar menyebutnya dengan nama Candi Sumberjati berlokasi di Dusun Krajan, Desa Sumberjati, Kecamatan Kademangan, Kabupaten Blitar. Berjarak sekitar tujuh kilomater dari Kota Blitar ke arah selatan. Berada dekat dengan pusat Kec. Kademangan, menjadikan candi ini memiki akses yang mudah serta fasilitas yang memadai untuk dikunjungi karena berada di tengah – tengah pemukiman warga. Berbeda dengan candi lain yang berdiri tegak dengan bagian bagian candinya, di Candi Simping ini hanya tersisa sebagian saja bahkan bisa dikatakan hampir rata dengan tanah. Namun, dari reruntuhan ini masih bisa dinikmati dan dipelajari sisa dari peradaban masa Kerajaan Majapahit.\n\nYang tersisa di candi ini hanya bagian batur atau dasar dari struktur candi yang masih terlihat utuh di tempatnya. Sedangkan bagian lain seperti bagian tubuh dan atap candi tercecer di sekitar candi. Candi ini menghadap ke barat yang ditandai dengan adanya undak atau tangga masuk menuju ruang utama pada candi. Ukuran dari bagian bawah candi atau dinamakan batur candi adalah panjang 7,5 meter, lebar 6 meter dan tinggi 0,75 meter dengan hiasan relief di sisi – sisinya berupa binatang binatang seperti singa, angsa, merak, burung garuda, babi hutan dan kera. Di tengah bangunan candi terdapat sebuah batu tempat abu jenazah Raden Wijaya disemayamkan berbentuk kubus yang memiliki panjang, lebar dan tinggi 75 cm. Pada bagian atas batu kubus tersebut ada relief bulus dan naga yang saling mengaitkan seolah mengitari batu ini.",
            "Prigen Pasuruan - Jawatimur\n\nCandi Jawi terletak di Desa Candi Wates, Kecamatan Prigen, Kabupaten Pasuruan, atau di kaki Gunung Welirang yang berjarak 31 km dari Kabupaten Pasuruan. Candi Jawi telah mengalami berkali – kali pemugaran, diantaranya pada tahun 1938 – 1941 ketika kondisinya runtuh. Namun pada pemugaran tersebut tidak dapat diselesaikan karena banyaknya bagian yang hilang dan baru disempurnakan pada pemugaran tahun 1975- 1980.\n\nKitab Negarakertagama pupuh 56 menyebutkan bahwa Candi Jawi didirikan atas perintah dari raja Kertanegara untuk tempat beribadah umat Syiwa Buddha. Raja Kertanegara merupakan penganut dari Syiwa Buddha dari Kerajaan Singasari. Selain sebagai tempat beribadah, Candi Jawi juga merupakan tempat perabuan jenazah Kertanegara. Hal terebut memang agak mengherankan mengingat letak Candi Jawi yang berjarak cukup jauh dengan pusat Kerajaan Singasari.\n\nHal tersebut diduga dengan alasan bahwa desa tersebut sangat patuh dengan Kertanegara serta memiliki penganut Syiwa Buddha yang sangat banyak. Dugaan tersebut juga didasari atas kejadian ketika Raden Wijaya, menantu Kertanegara yang dikejar oleh Jayakatwang, Raden Wijaya sempat bersembunyi di tempat ini sebelum akhirnya mengungsi ke Madura.",
            "Magelang - Jawa Timur\n\nBelum bisa dipastikan kapan candi Mendut dibangun karena memang sumbernya belum akurat. Namun ada rujukan dari beberapa peneliti mengenai pembangunan candi mendut yaitu pada 824 M. Angka 824 M ini didapat oleh J.G. De Casparis atas dasar penemuan prasasti yang ditemukan di Karang Tengah yang menyebutkan bahwa raja Indra telah membangun bangunan suci bernama Venuwana.\n\nCasparis menyebutkan bahwa Venuwana berarti hutan bambu sedangkan daerah Candi Mendut sendiri dahulu adalah hutan bambu maka dapat disimpulkan bangunan suci tersebut adalah Candi Mendut. Diperkirakan candi mendut berusia lebih tua dari pada Candi Borobudur.",
            "Klaten - Jawa Tengah\n\nCandi Sojiwan atau Candi Sajiwan adalah salah satu dari banyaknya candi di Klaten. Candi ini terletak di Dukuh Kalongan, Desa Kebon Dalem Kidul, Kecamatan Prambanan, Kabupaten Klaten yang berada pada ketinggian 146 – 150 mdpl. Candi ini dianggap sebagai candi sebaran dari Candi Prambanan karena letaknya yang tak jauh dari Candi Prambanan yaitu sekitar dua kilometer ke arah tenggara.\n\nCandi Sojiwan memiliki luas yaitu 8.140 m persegi, luas bangunan utama candi memiliki luas 401,3 m persegi dan tinggi candi kurang lebih 27 m. Candi Sojiwan menghadap kearah barat. Terdapat dwarapala yang sudah rusak dan kini ditempatkan di pos penjagaan di komplek Candi Sojiwan. Pada bagian bawah candi terdapat ukiran relief kisah satwa Jataka sekitar 12 adegan mengelilingi dinding bawah candi. Cara membaca relief tersebut dengan membaca ke arah selatan (mapradaksina).",
            "Probolinggo - Jawa Timur\n\nCandi Jabung terletak di Desa Jabung, Kecamatan Paiton, Kabupaten Probolinggo, Jawa Timur. Candi Jabung merupakan peninggalan Kerajaan Majapahit yang dibangun pada tahun 1354 M. Pada kitab Negarakertagama dikatakan bahwa Raden Hayam Wuruk pernah mengunjungi Candi Jabung pada tahun 1359 M. Pada kitab Pararaton mengatakan bahwa diperkirakan candi ini dibangun untuk pemakaman Bhra Gundul salah seroang keluarga raja.\n\nCandi Jabung terdiri dari dua bangunan yaitu candi utama dan satu bangunan yang lebih kecil. Yang menarik dari candi ini adalah bahan dasarnya yang terbuat dari batu bata merah berkualitas tinggi yang diukir dalam bentuk relief. Struktur bangunan yang terbuat dari candi ini mampu bertahan hingga ratusan tahun.\n\nCandi utama terbuat dari batu bata merah dengan ukuran panjang 13,11 meter, lebar 9,58 meter dan tinggi 15,58 meter. Jika dilihat dari segi arsitekturnya, Candi Jabung memiliki keunikan yaitu bentuk tubuhnya yang berbentuk bulat (silinder) yang terdiri dari bagian kaki candi bertingkat tiga berbentuk persegi. Sedangkan pada bagian atap berbentuk stupa. Letak pintu bilik candi berada pada sisi sebelah barat, maka Candi Jabung menghadap arah barat.",
            "Garut - Jawa Barat\n\nCandi Cangkuang terletak di Kampung Pulo, Desa Cangkuang, Kecamatan Leles, Kabupaten Garut. Desa Cangkuang dikelilingi oleh empat gunung diantaranya Gunung Keledong, Gunung Mandalawangi, Gunung Haruman, dan Gunung Guntur. Nama “Cangkuang” pada Candi Cangkuang diambil dari nama tanaman sejenis pandan (pandanus furcatus) yang banyak ditemukan di sekitar makam Embah Dalem Arief Muhammad, seorang leluhur dari Kampung Pulo.\n\nPemugaran Candi Cangkuang dilakukan pada tahun 1974-1975 sedangkan rekonstruksi dilakukan pada tahun 1976 yang meliputi kerangka badan, atap dan arca Syiwa serta dibuatkan joglo yang berfungsi menyimpan benda – benda temuan bersejarah di  seluruh Kabupaten Garut. Kegiatan pemugaran pada tahun 1974 telah menemukan bagian kaki candi. Kendala dalam rekonstruksi candi adalah hanya ditemukan 40% bagian candi aslinya, sehingga dibutuhkan batuan pengganti untuk merekonstruksi candi.\n\nDiduga Candi Cangkuang dibangun pada abad ke – 8 yang didasarkan pada tingkat kelapukan batuan dan kesederhanaan bentuk (tidak adanya relief). Setelah dipugar, Candi Cangkuang memiliki tinggi 8,5 meter dengan kaki candi berukuran 4,5 x 4,5 meter. Atap candi berbentuk piramid. Sepanjang tepian atap candi terdapat semacam mahkota kecil yang memiliki kemiripan dengan atap candi yang ada di Candi Gedong Songo.",
    };

    private static final int[] imageCandi = {
            R.drawable.singosari,
            R.drawable.gambarwetan,
            R.drawable.penataran,
            R.drawable.borobudur,
            R.drawable.prambanan1,
            R.drawable.dieng,
            R.drawable.badut,
            R.drawable.lumbung,
            R.drawable.gedongsongo,
            R.drawable.simping,
            R.drawable.jawi,
            R.drawable.mendut,
            R.drawable.sojiwan,
            R.drawable.jabung,
            R.drawable.cangkuang1,


    };

    static ArrayList<Candi> getListData(){
        ArrayList<Candi> list = new ArrayList<>();
        for (int position = 0; position < urutanCandi.length; position++){
            Candi candi = new Candi();
            candi.setNama(urutanCandi[position]);
            candi.setDetail(detailCandi[position]);
            candi.setPhoto(imageCandi[position]);
            list.add(candi);
        }
        return list;
    }
}

